apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sergeyognev-com
spec:
  secretName: sergeyognev-com-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - sergeyognev.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.sergeyognev.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer