---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - {{ .Values.frontend.host }}
      secretName: {{ .Values.frontend.secret }}
  rules:
  - host: {{ .Values.frontend.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.frontend.port }}