# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret-frontend
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1IjogewoJCQkiYXV0aCI6ICJjM1JrTFRBeE55MHdNRGc2TFdaV1ZWSnBPWEZJYVRsbk0xbGlSRnBPTWxjPSIKCQl9LAoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4Tnkwd01EZzZjalpNVVVOUVFtUllNMnRpWW5kemJ6ZHJYM2c9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson