---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-backend
  labels:
    app: momo-backend
spec:
  replicas: 1
  revisionHistoryLimit: 15
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 80%
      maxSurge: 20%
  selector:
    matchLabels:
      app: momo-backend
  template:
    metadata:
      labels:
        app: momo-backend
    spec:
      containers:
        - name: momo-backend
          image: gitlab.praktikum-services.ru:5050/std-017-008/momo-store/momo-backend:1.0.959001
          imagePullPolicy: IfNotPresent
          ports:
            - name: momo-backend
              containerPort: 8081
      imagePullSecrets:
        - name: docker-config-secret-backend